version: '2'
services:
  base: &base
    image: ruby:2.4.0
    working_dir: /home/app/active_ext
    volumes:
      - .:/home/app/active_ext
      - active_ext_gems_2_4_0:/usr/local/bundle

  #################### CONTAINERS ####################

  active_ext:
    <<: *base
    container_name: active_ext
    command: /bin/bash -c 'bundle install && bundle exec rspec'

volumes:
  active_ext_gems_2_4_0:
